### ISSUE TITLE
Soul Speed False Flag and Soft Ban

### ISSUE THREAD

**Issue by tkn0** [MSWS/NOPE#155] opened 2020-07-01 04:09 UTC
**What server version are you running?**
1.16.1 Spigot? Whatever the test server is.

**What Minecraft Client Version are you running?**
1.16.1 Vanilla

**What version of NOPE are you running?**
1.7.1 - test server version if this isn't it (I can't log on)

**What is the debug ID?**
Unsure

**Is there any debug information? (Please include average info if available)**
Unsure

**What is causing this false positive?**
https://www.youtube.com/watch?v=6QJOvf2WqNg&t=1s

**Is this false positive reproducible on the test server?**
Yes, it was found on the test server!

**Comment by tkn0** [comment] 2020-07-01 04:17
I don't think this IndexOutOfBoundsException is with this flag only as I keep getting it randomly.

**Comment by tkn0** [comment] 2020-07-01 04:21
I feel like this is a major issue as it prevents players from even playing the server. :(

**Comment by MSWS** [comment] 2020-07-01 04:22
The IndexOutOfBoundsException is caused by ProtocolLib and not NOPE.

**Comment by tkn0** [comment] 2020-07-01 04:24
Thanks :) Will it be fixed when Protocol Lib updates?

**Comment by MSWS** [comment] 2020-07-01 04:24
Yes

**Comment by tkn0** [comment] 2020-07-01 04:24
All my plugins are broke from protocol smh

**Comment by steviebeenz** [comment] 2020-07-01 04:25
That's why it's better to use the Viaver api rather than the P-Lib or Vanilla one as it is always the same and up to date with in 2 days.

**Comment by tkn0** [comment] 2020-07-01 04:25
Anyway, insights on the soul speed?

**Comment by tkn0** [comment] 2020-07-01 04:26
Viaver api?

**Comment by steviebeenz** [comment] 2020-07-01 04:27
Viaversion/Viabackwards api.

**Comment by MSWS** [comment] 2020-07-01 05:05
This should be fixed in 1.7.2.

**Closed as completed by MSWS** 2020-07-01 05:05 UTC
Labels: False Positive
