### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DumplingSaint** [MSWS/NOPE#125] opened 2020-06-18 03:08 UTC
**What server version are you running?**
_Please include Minecraft Version, and Bukkit/Spigot/Bungee_

1.15.2 Paper-332

**What version of NOPE are you running?**
_You can find this out by running /nope ingame_

1.61

**What is the bug?**
_Please be descriptive_
Part of NOPE player esp crashed the plugin

**Please list your plugins below**
https://gyazo.com/ed4d1c181dab48cc98b2c97f1949c568

**Is there anything else to add?**
_Are there any error logs?_
[22:33:13 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-332 (MC: 1.15.2) ---
>.... [22:33:13 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [22:33:13 ERROR]: ------------------------------
>.... [22:33:13 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [22:33:13 ERROR]: ------------------------------
>.... [22:33:13 ERROR]: Current Thread: Server thread
>.... [22:33:13 ERROR]: PID: 18 | Suspended: false | Native: false | State: RUNNABLE
>.... [22:33:13 ERROR]: Stack:
>.... [22:33:13 ERROR]: java.util.AbstractCollection.toArray(AbstractCollection.java:141)
>.... [22:33:13 ERROR]: java.util.ArrayList.<init>(ArrayList.java:178)
>.... [22:33:13 ERROR]: org.bukkit.craftbukkit.v1_15_R1.CraftServer.getWorlds(CraftServer.java:704)
>.... [22:33:13 ERROR]: org.bukkit.Bukkit.getWorlds(Bukkit.java:533)
>.... [22:33:13 ERROR]: xyz.msws.nope.modules.npc.NPC.<init>(NPC.java:74)
>.... [22:33:13 ERROR]: xyz.msws.nope.checks.packet.PlayerESP1.spawnNPCs(PlayerESP1.java:144)
>.... [22:33:13 ERROR]: xyz.msws.nope.checks.packet.PlayerESP1.onJoin(PlayerESP1.java:104)
>.... [22:33:13 ERROR]: com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor661.execute(Unknown Source)
>.... [22:33:13 ERROR]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [22:33:13 ERROR]: org.bukkit.plugin.EventExecutor$$Lambda$2273/498924699.execute(Unknown Source)
>.... [22:33:13 ERROR]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [22:33:13 ERROR]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [22:33:13 ERROR]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:238)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.PlayerList.lambda$null$0(PlayerList.java:175)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.PlayerList$$Lambda$5011/1564821258.run(Unknown Source)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:343)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:140)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1344)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173)
>.... [22:33:13 ERROR]: net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962)
>.... [22:33:13 ERROR]: java.lang.Thread.run(Thread.java:748)

**Comment by MSWS** [comment] 2020-06-18 03:15
Does this happen on 1.6.2?

**Comment by DumplingSaint** [comment] 2020-06-19 05:23
Yes.

**Comment by MSWS** [comment] 2020-06-19 06:33
![](https://github.trello.services/images/mini-trello-icon.png) [KA Crash](https://trello.com/c/EYxlid8E/169-ka-crash)

**Comment by MSWS** [comment] 2020-06-19 06:35
This is a duplicate of #127

**Closed as completed by MSWS** 2020-06-19 06:35 UTC
Labels: Bug
